### ISSUE TITLE
Question: Automatically claim or return the next empty plot via code

### ISSUE THREAD

**Issue by McJeffr** [IntellectualSites/PlotSquared#1666]
**Description of the problem:** 
This is more of a question than a problem, though there seems to be a few differences between the plotsquared-api on Maven and the actual PlotSquared-Bukkit version.

I am currently using the latest version of the plotsquared-api from the Maven repository (which is indeed missing the api package, as already reported 18 days ago) to create some additional custom functionalities on top of PlotSquared. However, I can't seem to figure out a way to call the /plot auto command from code (players on this server are not supposed to execute this command and they don't have permissions for it, hence the reason I need to execute it via code). In fact, any method or other functionality to automatically claim a plot for a user will do. Whether this is finding the first empty plot and returning it or having a method that automatically claims this first empty plot.

Since the javadocs seem to be temporarily unavailable right now, I have taken a look at some of the other possibilities in the actual commands. I have found that the "Auto" class contains some methods for claiming a plot in the plotsquared-api, but when calling on these methods in the server they all return `java.lang.NoSuchMethodError`s. These are the methods `Auto.autoClaimSafe()`, `Auto.homeOrAuto()` and `Auto.getNextPlot()`

That leaves me to my question:
**Is there any way to return the next empty plot in a plotworld or automatically claim the next empty plot in a plot world via code?**

**Extra details**
I am using:
- plotsquared-api (v. latest) from http://ci.athion.net/job/PlotSquared/ws/mvn/
- PlotSquared (v. 3.5.0-SNAPSHOT-95f8aaa) in the server
- The server I am working on is the latest 1.12 Spigot build.
- The server runs Java 1.8.0_60

For good reference, this is the error thrown when calling the `getNextPlot()` method:
`java.lang.NoSuchMethodError: com.intellectualcrafters.plot.commands.Auto.getNextPlot(Lcom/intellectualcrafters/plot/object/PlotId;)Lcom/intellectualcrafters/plot/object/PlotId;
	at net.qubion.qubioncore.command.claim.SCmdAuto.lambda$null$0(SCmdAuto.java:78) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-7228328-af1c013]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]`

**Checklist**:
- [] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
You are running an older version of PlotSquared on the server. Download the latest version from the CI:
ci.athion.net/job/PlotSquared/
