### ISSUE TITLE
PlotSquared not clearing the entire plot

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#2586]
# NOTICE: 
```diff
! PlotSquared for Minecraft Java Edition versions between 1.7 through to 1.12.2 are considered
! legacy, and will receive limited to no support. Please consider upgrading to 1.13+ for
! future support.  Plugins exist for 1.13+ which bring back behaviors found in 1.8.8
! All versions of PlotSquared for Sponge and Nukkit(X) will recieve limited to no support
! due to lack of developer interest and time. Additionally, NukkitX has not had feature
! updates since the Better Together, which prevents some PlotSquared features from ever
! functioning.  Contributions are always welcome however!
```

**Feature requests & Suggestions are to be submitted at the [PlotSquared Suggestions tracker](https://github.com/IntellectualSites/PlotSquaredSuggestions)**

**Code contributions are to be done through [PRs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request), tagging the specific issue ticket(s) if applicable.**

**[DISCORD INVITE LINK](https://discord.gg/cSMxtGn)** and please, for the love of the little sanity we have left, use the correct channels!

# BUG REPORT TEMPLATE:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):
worlds.yml: https://pastebin.com/4QUjDJHn
settings.yml https://pastebin.com/JQu1Vraj
PlotSquared version: PlotSquared-4.383

### Server type:
**select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [X] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

``` git-Paper-a9c95b59 (MC: 1.13.2) ```

### WorldEdit/FAWE versions:

- [X] FAWE *version*: FastAsyncWorldEdit-bukkit-1.13.198.jar
- [] WorldEdit *version*: 

### Description of the problem:
Clearing a plot doesn't entirely clear it. I've had a lot of players complaining about it, here's an example of me trying to clear the plot for the user to see if it would work but it didn't clear everything:
![2019-11-15_18 42 00](https://user-images.githubusercontent.com/10485646/68967504-6100e380-07d8-11ea-91af-d6b3da582c82.png)

### How to replicate:
This only started to become an issue when I updated FAWE from "FastAsyncWorldEdit-bukkit-1.13.191" to "FastAsyncWorldEdit-bukkit-1.13.198". I suspect this commit may have something to do with it: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/c1a0819acb2ab73615bbb05f8c81c248f736fd33

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by MattBDev** [comment]
Can you try to reproduce this issue using PlotSquared 4.440

**Comment by SecretlyJealous** [comment]
> Can you try to reproduce this issue using PlotSquared 4.440

Yes, I'll try that when I next restart

**Comment by MattBDev** [comment]
@SecretlyJealous Did you get a chance to test the newest version?

**Comment by SecretlyJealous** [comment]
> @SecretlyJealous Did you get a chance to test the newest version?

Not yet, I still need to resolve some other plugins breaking due to https://github.com/IntellectualSites/PlotSquared/commit/37f608258fcbc016e5603414d41cf698a1bba9a1
Example: 
```
java.lang.NoSuchMethodError: com.github.intellectualsites.plotsquared.plot.object.Location.getChunkLoc()Lcom/github/intellectualsites/plotsquared/plot/object/ChunkLoc;
at eu.creativefun.creativefunedit.commands.Commands.set(Commands.java:71) ~[?:?]
at eu.creativefun.creativefunedit.commands.SetCommand.runCommand(SetCommand.java:43) ~[?:?]
at eu.creativefun.creativefunedit.Listeners$1.run(Listeners.java:35) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[server.jar:git-Paper-225]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[server.jar:git-Paper-225]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[server.jar:git-Paper-225]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by SecretlyJealous** [comment]
This is still an issue using PlotSquared 4.440

**Comment by Sauilitired** [comment]
Cannot replicate with recent FAWE and PlotSquared versions.
